// Editor window constants for vizero
#ifndef VIZERO_EDITOR_WINDOW_CONSTANTS_H
#define VIZERO_EDITOR_WINDOW_CONSTANTS_H

#define MAX_WINDOWS 16
#define DEFAULT_TITLE_BAR_HEIGHT 24
#define DEFAULT_MIN_WIDTH 100
#define DEFAULT_MIN_HEIGHT 40

#endif // VIZERO_EDITOR_WINDOW_CONSTANTS_H
